package main

import (
	"strings"
	"testing"
)

func TestGenerate(t *testing.T) {
	t.Parallel()

	got := generate()
	for _, want := range []string{
		"// Code generated by cmd/simgen from internal/sim. DO NOT EDIT.",
		"export const WEAPONS = ['autoCannon', 'rockets', 'bigSpaceGun', 'zapper'] as const;",
		"export const TICK_RATE = 60;",
		"  autoCannon: {\n    interval: 0.13,",
		"export const LAYOUT = {\n  ticks: 0,",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generate() should contain %q", want)
		}
	}
	if got != generate() {
		t.Error("generate() differs between runs; drift checks need it stable")
	}
}
