package main

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/starquake/voidmarch/internal/sim"
	"github.com/starquake/voidmarch/internal/simbridge"
)

// endObject closes an object literal of constants.
const endObject = "} as const;\n\n"

// generate is the TypeScript module, deterministic so drift is a diff.
func generate() string {
	var b strings.Builder
	w := func(format string, args ...any) {
		fmt.Fprintf(&b, format, args...)
	}
	w("// Code generated by cmd/simgen from internal/sim. DO NOT EDIT.\n\n")
	writeLists(w)
	writeTunables(w)
	writeLayout(w)

	return b.String()
}

// writer writes formatted text to the module.
type writer func(format string, args ...any)

// writeLists writes the id lists and their types.
func writeLists(w writer) {
	w("/** Weapons in index order, as the WebAssembly sim numbers them. */\n")
	w("export const WEAPONS = %s as const;\n", list(sim.Weapons()))
	w("/** Engines in index order. */\n")
	w("export const ENGINES = %s as const;\n", list(sim.Engines()))
	w("/** Shields in index order. */\n")
	w("export const SHIELDS = %s as const;\n", list(sim.Shields()))
	w("/** Enemy classes in index order, matching the server's EnemyKind. */\n")
	w("export const ENEMY_KINDS = %s as const;\n", list(sim.EnemyKinds()))
	w("/** Projectile kinds in index order: the weapons, then the enemy bullets. */\n")
	w("export const PROJECTILE_KINDS = %s as const;\n", list(simbridge.ProjectileKinds()))
	w("/** Factions in index order: this player's, another player's, an enemy's. */\n")
	w("export const FACTIONS = %s as const;\n\n", list(simbridge.Factions()))

	w("export type WeaponId = (typeof WEAPONS)[number];\n")
	w("export type EngineId = (typeof ENGINES)[number];\n")
	w("export type ShieldId = (typeof SHIELDS)[number];\n")
	w("export type EnemyKind = (typeof ENEMY_KINDS)[number];\n")
	w("export type ProjectileKind = (typeof PROJECTILE_KINDS)[number];\n")
	w("export type EnemyBulletId = Exclude<ProjectileKind, WeaponId>;\n")
	w("export type Faction = (typeof FACTIONS)[number];\n\n")
}

// writeTunables writes the rules' numbers the scenes read.
func writeTunables(w writer) {
	d := sim.DefaultLoadout()
	w("/** The parts every new player starts with. */\n")
	w(
		"export const DEFAULT_LOADOUT = { weapon: %q, engine: %q, shield: %q, weaponTier: 0, engineTier: 0, shieldTier: 0 } as const;\n\n",
		d.Weapon,
		d.Engine,
		d.Shield,
	)

	w("export const TICK_RATE = %d;\n", sim.TickRate)
	w("export const TICK_SECONDS = 1 / TICK_RATE;\n")
	w("export const MAX_TICKS_PER_FRAME = %d;\n", sim.MaxTicksPerFrame)
	w("export const SECTOR_RADIUS = %d;\n", sim.SectorRadius)
	w("export const GRID_RINGS = %d;\n", sim.GridRings)
	w("export const WORLD_APOTHEM = %s;\n", num(sim.WorldApothem))
	w("export const WORLD_EDGE_BAND = %d;\n", sim.WorldEdgeBand)
	w("export const SAFE_ZONE_RADIUS = %d;\n", sim.SafeZoneRadius)
	w("export const DERELICT_HOLD_RADIUS = %d;\n", sim.DerelictHoldRadius)
	w("export const SHIP_RADIUS = %d;\n", sim.ShipRadius)
	w("export const MAX_DAMAGE = %d;\n", sim.MaxDamage)
	w("export const RESPAWN_DELAY = %s;\n", num(sim.RespawnDelay))
	w("export const HOME_SPAWN_Y = %d;\n", sim.HomeSpawnY)
	w("export const BRAIN_SPACING = %d;\n", sim.BrainSpacing)
	w("export const RAM_DAMAGE = %d;\n", sim.RammingDamage)
	w("export const RAM_SPEED = %s;\n", num(sim.RammingSpeed))
	w("export const SHARD_DAMAGE = %s;\n", num(sim.ShotDamage(sim.ProjectileShard)))
	w("/** Tier names from plain to Hyper; the index is the tier. */\n")
	w("export const TIER_NAMES = %s as const;\n", list(tierNames()))
	w("export const MAX_TIER = %d;\n", sim.TierHyper)
	w("export const PICKUP_LIFETIME = %s;\n", num(sim.PickupLifetime))
	w("export const PICKUP_REACH = %s;\n\n", num(sim.PickupReach))

	writeShieldStats(w)

	w("export const ENGINE_STATS = {\n")
	for _, id := range sim.Engines() {
		s := sim.EngineStatsOf(id)
		w(
			"  %s: { acceleration: %s, maxSpeed: %s, drag: %s },\n",
			id,
			num(s.Acceleration),
			num(s.MaxSpeed),
			num(s.Drag),
		)
	}
	w(endObject)

	w("export const WEAPON_STATS = {\n")
	for _, id := range sim.Weapons() {
		s := sim.WeaponStatsOf(id)
		muzzles := make([]string, 0, len(s.Muzzles))
		for _, m := range s.Muzzles {
			muzzles = append(
				muzzles,
				fmt.Sprintf("{ forward: %s, right: %s }", num(m.Forward), num(m.Right)),
			)
		}
		w("  %s: {\n", id)
		w(
			"    interval: %s,\n    charge: %s,\n    damage: %s,\n",
			num(s.Interval),
			num(s.Charge),
			num(s.Damage),
		)
		w("    speed: %s,\n    lifetime: %s,\n", num(s.Speed), num(s.Lifetime))
		w("    muzzles: [%s],\n", strings.Join(muzzles, ", "))
		w("    alternate: %t,\n    shake: %s,\n", s.Alternate, num(s.Shake))
		w("  },\n")
	}
	w(endObject)

	writeEnemies(w)
}

// writeEnemies writes the enemies' hit circles and the Frigate's numbers
// the client draws with.
func writeEnemies(w writer) {
	w("/** Hit circles in art pixels, from the sprites' opaque extent. */\n")
	w("export const ENEMY_RADIUS = {\n")
	for _, k := range sim.EnemyKinds() {
		w("  %s: %s,\n", k, num(sim.EnemyRadius(k)))
	}
	w(endObject)
	w("export const FRIGATE_REACH = %d;\n", sim.FrigateReach)
	w("export const FRIGATE_SHIELD = %d;\n", sim.FrigateShield)
	w("export const DREADNOUGHT_SHIELD = %d;\n", sim.DreadnoughtShield)
	w("export const DREADNOUGHT_HP = %d;\n", sim.DreadnoughtHP)
}

// writeShieldStats writes each shield's arc, charges and recharge time.
func writeShieldStats(w writer) {
	w("export const SHIELD_STATS = {\n")
	for _, id := range sim.Shields() {
		s := sim.ShieldStatsOf(id)
		w(
			"  %s: { coverage: %s, strength: %s, recharge: %s },\n",
			id,
			num(s.Coverage),
			num(s.Strength),
			num(s.Recharge),
		)
	}
	w(endObject)
}

// writeLayout writes where the state sits in the WebAssembly sim's array.
func writeLayout(w writer) {
	w("/** Where the WebAssembly sim's state sits in its float64 array (internal/simbridge). */\n")
	w("export const LAYOUT = {\n")
	fields := []struct {
		name  string
		value int
	}{
		{"ticks", simbridge.HeaderTicks},
		{"alpha", simbridge.HeaderAlpha},
		{"shipX", simbridge.HeaderShipX},
		{"shipY", simbridge.HeaderShipY},
		{"shipVX", simbridge.HeaderShipVX},
		{"shipVY", simbridge.HeaderShipVY},
		{"shipAngle", simbridge.HeaderShipAngle},
		{"shipThrusting", simbridge.HeaderShipThrusting},
		{"shipCooldown", simbridge.HeaderShipCooldown},
		{"shipCharging", simbridge.HeaderShipCharging},
		{"shipNextMuzzle", simbridge.HeaderShipNextMuzzle},
		{"shipDamage", simbridge.HeaderShipDamage},
		{"shipRotationSnap", simbridge.HeaderShipRotationSnap},
		{"shipWeapon", simbridge.HeaderShipWeapon},
		{"shipEngine", simbridge.HeaderShipEngine},
		{"shipShield", simbridge.HeaderShipShield},
		{"shipShieldCharge", simbridge.HeaderShipShieldCharge},
		{"shipSinceHit", simbridge.HeaderShipSinceHit},
		{"shipDownFor", simbridge.HeaderShipDownFor},
		{"shipRevive", simbridge.HeaderShipRevive},
		{"shipWeaponTier", simbridge.HeaderShipWeaponTier},
		{"shipEngineTier", simbridge.HeaderShipEngineTier},
		{"shipShieldTier", simbridge.HeaderShipShieldTier},
		{"previousX", simbridge.HeaderPreviousX},
		{"previousY", simbridge.HeaderPreviousY},
		{"shots", simbridge.HeaderShots},
		{"charges", simbridge.HeaderCharges},
		{"expired", simbridge.HeaderExpired},
		{"projectileCapacity", simbridge.ProjectileCapacity},
		{"poolOffset", simbridge.PoolOffset},
		{"projectileSize", simbridge.ProjectileSize},
		{"projectileActive", simbridge.ProjectileActive},
		{"projectileKind", simbridge.ProjectileKind},
		{"projectileFaction", simbridge.ProjectileFaction},
		{"projectileX", simbridge.ProjectileX},
		{"projectileY", simbridge.ProjectileY},
		{"projectileAngle", simbridge.ProjectileAngle},
		{"projectileAge", simbridge.ProjectileAge},
		{"projectileShotId", simbridge.ProjectileShotID},
		{"projectileShard", simbridge.ProjectileShard},
		{"shotsOffset", simbridge.ShotsOffset},
		{"shotSize", simbridge.ShotSize},
		{"shotId", simbridge.ShotID},
		{"shotWeapon", simbridge.ShotWeapon},
		{"shotMuzzle", simbridge.ShotMuzzle},
		{"shotX", simbridge.ShotX},
		{"shotY", simbridge.ShotY},
		{"shotAngle", simbridge.ShotAngle},
		{"chargesOffset", simbridge.ChargesOffset},
		{"expiredOffset", simbridge.ExpiredOffset},
		{"expiredSize", simbridge.ExpiredSize},
		{"expiredKind", simbridge.ExpiredKind},
		{"expiredFaction", simbridge.ExpiredFaction},
		{"expiredX", simbridge.ExpiredX},
		{"expiredY", simbridge.ExpiredY},
		{"expiredShotId", simbridge.ExpiredShotID},
		{"expiredSlot", simbridge.ExpiredSlot},
		{"stateSize", simbridge.StateSize},
		{"maxTargets", simbridge.MaxTargets},
		{"targetSize", simbridge.TargetSize},
		{"shipTargetSize", simbridge.ShipTargetSize},
		{"bumpSize", simbridge.BumpSize},
		{"scratchSize", simbridge.ScratchSize},
	}
	for _, f := range fields {
		w("  %s: %d,\n", f.name, f.value)
	}
	w("} as const;\n")
}

func list[T ~string](items []T) string {
	quoted := make([]string, 0, len(items))
	for _, it := range items {
		quoted = append(quoted, "'"+string(it)+"'")
	}

	return "[" + strings.Join(quoted, ", ") + "]"
}

// num writes a float so JavaScript reads back the same double.
func num(v float64) string {
	const float64Bits = 64

	return strconv.FormatFloat(v, 'g', -1, float64Bits)
}

// tierNames are the tiers' names, plain first.
func tierNames() []string {
	names := make([]string, 0, sim.TierHyper+1)
	for t := sim.TierPlain; t <= sim.TierHyper; t++ {
		names = append(names, t.Name())
	}

	return names
}
