// Writes src/bootsizes.gen.ts: the size of every file the game loads before
// play, for the loading bar (#227, decision 9). build.mjs runs it once the
// game's bundles are built, since their sizes are in it, and before the entry
// module, which imports it; the entry's own size is never in it, as it has
// loaded before the bar starts.
import { stat } from 'node:fs/promises';
import path from 'node:path';

import { bootUrls } from '../src/preload.ts';

/** What the game's bundles import, as esbuild's metafile records it. */
export interface Metafile {
  outputs: Record<string, { imports: { path: string; kind: string; external?: boolean }[] }>;
}

/** Where the files come from. */
export interface Sources {
  /** The built bundles, served as /static/js/. */
  jsDir: string;
  /** Everything else, served as /static/. */
  staticDir: string;
  /** The directory esbuild's metafile paths are relative to. */
  workingDir: string;
  /** The metafiles of the game's builds. */
  metafiles: Metafile[];
}

const STATIC = '/static/';
const JS = '/static/js/';

/** Every module main.js loads before it runs, main.js first, as /static/js/ URLs. */
export function gameModules({ jsDir, workingDir, metafiles }: Sources): string[] {
  const imports = new Map<string, string[]>();
  for (const meta of metafiles) {
    for (const [out, { imports: list }] of Object.entries(meta.outputs)) {
      const file = path.resolve(workingDir, out);
      const statics = list.filter((i) => i.kind === 'import-statement');
      imports.set(
        file,
        statics.map((i) => (i.external === true ? path.resolve(path.dirname(file), i.path) : path.resolve(workingDir, i.path))),
      );
    }
  }
  const seen = new Set<string>();
  const visit = (file: string): void => {
    if (!seen.has(file)) {
      seen.add(file);
      for (const next of imports.get(file) ?? []) {
        visit(next);
      }
    }
  };
  visit(path.join(jsDir, 'main.js'));

  return [...seen].map((file) => JS + path.relative(jsDir, file).split(path.sep).join('/'));
}

/** The file a URL serves. */
function fileOf(url: string, { jsDir, staticDir }: Sources): string {
  if (url.startsWith(JS)) {
    return path.join(jsDir, url.slice(JS.length));
  }
  if (url.startsWith(STATIC)) {
    return path.join(staticDir, url.slice(STATIC.length));
  }
  throw new Error(`${url} is not served from ${STATIC}`);
}

const sizeOf = async (url: string, sources: Sources): Promise<number> => (await stat(fileOf(url, sources))).size;

/** The format of a sound's URL: its extension. */
const formatOf = (url: string): string => path.extname(url).slice(1);

/** The source of bootsizes.gen.ts. */
export async function bootSizesSource(sources: Sources): Promise<string> {
  const code = await Promise.all(gameModules(sources).map(async (url) => `  ${JSON.stringify(url)}: ${String(await sizeOf(url, sources))},`));
  const files = await Promise.all(
    bootUrls().map(async ({ key, urls }) => {
      const [only] = urls;
      if (urls.length === 1 && only !== undefined) {
        return `  ${JSON.stringify(key)}: ${String(await sizeOf(only, sources))},`;
      }
      const formats = await Promise.all(urls.map(async (url) => `${formatOf(url)}: ${String(await sizeOf(url, sources))}`));

      return `  ${JSON.stringify(key)}: { ${formats.join(', ')} },`;
    }),
  );

  return [
    '// Code generated by frontend/build.mjs from internal/web/static. DO NOT EDIT.',
    '',
    "import type { FileBytes } from './sim/loading.ts';",
    '',
    "/** The game's code in bytes, by URL: main.js and every module it imports. */",
    'export const CODE_BYTES: Readonly<Record<string, number>> = {',
    ...code,
    '};',
    '',
    '/** Every other file loaded before play, by loader key: its bytes, or a sound\'s per format, best first. */',
    'export const FILE_BYTES: Readonly<Record<string, FileBytes>> = {',
    ...files,
    '};',
    '',
  ].join('\n');
}
