// Code generated by cmd/simgen from internal/sim. DO NOT EDIT.

/** Weapons in index order, as the WebAssembly sim numbers them. */
export const WEAPONS = ['autoCannon', 'rockets', 'bigSpaceGun', 'zapper'] as const;
/** Engines in index order. */
export const ENGINES = ['base', 'bigPulse', 'burst', 'supercharged'] as const;
/** Shields in index order. */
export const SHIELDS = ['front', 'frontAndSide', 'round', 'invincibility'] as const;
/** Enemy classes in index order, matching the server's EnemyKind. */
export const ENEMY_KINDS = ['scout', 'fighter'] as const;
/** Projectile kinds in index order: the weapons, then the enemy bullets. */
export const PROJECTILE_KINDS = ['autoCannon', 'rockets', 'bigSpaceGun', 'zapper', 'klaedBullet', 'klaedBigBullet', 'shard'] as const;
/** Factions in index order: this player's, another player's, an enemy's. */
export const FACTIONS = ['own', 'remote', 'enemy'] as const;

export type WeaponId = (typeof WEAPONS)[number];
export type EngineId = (typeof ENGINES)[number];
export type ShieldId = (typeof SHIELDS)[number];
export type EnemyKind = (typeof ENEMY_KINDS)[number];
export type ProjectileKind = (typeof PROJECTILE_KINDS)[number];
export type EnemyBulletId = Exclude<ProjectileKind, WeaponId>;
export type Faction = (typeof FACTIONS)[number];

/** The parts every new player starts with. */
export const DEFAULT_LOADOUT = { weapon: "autoCannon", engine: "base", shield: "front" } as const;

export const TICK_RATE = 60;
export const TICK_SECONDS = 1 / TICK_RATE;
export const MAX_TICKS_PER_FRAME = 5;
export const WORLD_HALF_SIZE = 2000;
export const WORLD_EDGE_BAND = 200;
export const SAFE_ZONE_RADIUS = 300;
export const SHIP_RADIUS = 12;
export const MAX_DAMAGE = 3;
export const RESPAWN_DELAY = 3;
export const HOME_SPAWN_Y = 160;
export const BRAIN_SPACING = 40;
export const RAM_DAMAGE = 2;
export const RAM_SPEED = 120;
export const SHARD_DAMAGE = 2;

export const SHIELD_STATS = {
  front: { coverage: 1.5707963267948966, strength: 3, recharge: 5 },
  frontAndSide: { coverage: 3.141592653589793, strength: 2, recharge: 5 },
  round: { coverage: 6.283185307179586, strength: 1, recharge: 3 },
  invincibility: { coverage: 6.283185307179586, strength: 3, recharge: 12 },
} as const;

export const ENGINE_STATS = {
  base: { acceleration: 900, maxSpeed: 220, drag: 3.5 },
  bigPulse: { acceleration: 520, maxSpeed: 300, drag: 1.2 },
  burst: { acceleration: 1700, maxSpeed: 185, drag: 7 },
  supercharged: { acceleration: 1200, maxSpeed: 270, drag: 2 },
} as const;

export const WEAPON_STATS = {
  autoCannon: {
    interval: 0.13,
    charge: 0,
    damage: 1,
    speed: 520,
    lifetime: 0.9,
    muzzles: [{ forward: 9, right: -10.5 }, { forward: 9, right: 10.5 }],
    alternate: true,
    shake: 0,
  },
  rockets: {
    interval: 0.4,
    charge: 0,
    damage: 3,
    speed: 140,
    lifetime: 1.5,
    muzzles: [{ forward: 7, right: -12 }, { forward: 7, right: 12 }],
    alternate: true,
    shake: 0,
  },
  bigSpaceGun: {
    interval: 0.9,
    charge: 0.45,
    damage: 12,
    speed: 300,
    lifetime: 0.6666666666666666,
    muzzles: [{ forward: 16, right: 0 }],
    alternate: false,
    shake: 0.004,
  },
  zapper: {
    interval: 0.24,
    charge: 0.1,
    damage: 2,
    speed: 430,
    lifetime: 0.75,
    muzzles: [{ forward: 15, right: -11 }, { forward: 15, right: 11 }],
    alternate: false,
    shake: 0,
  },
} as const;

/** Hit circles in art pixels, from the sprites' opaque extent. */
export const ENEMY_RADIUS = {
  scout: 11,
  fighter: 12,
} as const;

/** Where the WebAssembly sim's state sits in its float64 array (internal/simbridge). */
export const LAYOUT = {
  ticks: 0,
  alpha: 1,
  shipX: 2,
  shipY: 3,
  shipVX: 4,
  shipVY: 5,
  shipAngle: 6,
  shipThrusting: 7,
  shipCooldown: 8,
  shipCharging: 9,
  shipNextMuzzle: 10,
  shipDamage: 11,
  shipRotationSnap: 12,
  shipWeapon: 13,
  shipEngine: 14,
  shipShield: 15,
  shipShieldCharge: 21,
  shipSinceHit: 22,
  shipDownFor: 23,
  shipRevive: 24,
  previousX: 16,
  previousY: 17,
  shots: 18,
  charges: 19,
  expired: 20,
  projectileCapacity: 256,
  poolOffset: 25,
  projectileSize: 9,
  projectileActive: 0,
  projectileKind: 1,
  projectileFaction: 2,
  projectileX: 3,
  projectileY: 4,
  projectileAngle: 5,
  projectileAge: 6,
  projectileShotId: 7,
  projectileShard: 8,
  shotsOffset: 2329,
  shotSize: 6,
  shotId: 0,
  shotWeapon: 1,
  shotMuzzle: 2,
  shotX: 3,
  shotY: 4,
  shotAngle: 5,
  chargesOffset: 2389,
  expiredOffset: 2394,
  expiredSize: 6,
  expiredKind: 0,
  expiredFaction: 1,
  expiredX: 2,
  expiredY: 3,
  expiredShotId: 4,
  expiredSlot: 5,
  stateSize: 3930,
  maxTargets: 128,
  targetSize: 4,
  shipTargetSize: 5,
  bumpSize: 8,
  scratchSize: 1024,
} as const;
