// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dreadnought.sql

package db

import (
	"context"
)

const dreadnoughts = `-- name: Dreadnoughts :many
SELECT faction, health, updated_at FROM dreadnoughts ORDER BY faction
`

func (q *Queries) Dreadnoughts(ctx context.Context) ([]Dreadnought, error) {
	rows, err := q.db.QueryContext(ctx, dreadnoughts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dreadnought
	for rows.Next() {
		var i Dreadnought
		if err := rows.Scan(&i.Faction, &i.Health, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDreadnought = `-- name: SaveDreadnought :exec
INSERT INTO dreadnoughts (faction, health, updated_at) VALUES (?, ?, ?)
ON CONFLICT (faction) DO UPDATE SET health = excluded.health, updated_at = excluded.updated_at
`

type SaveDreadnoughtParams struct {
	Faction   string
	Health    float64
	UpdatedAt int64
}

func (q *Queries) SaveDreadnought(ctx context.Context, arg SaveDreadnoughtParams) error {
	_, err := q.db.ExecContext(ctx, saveDreadnought, arg.Faction, arg.Health, arg.UpdatedAt)
	return err
}
