// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dreadnought.sql

package db

import (
	"context"
)

const dreadnought = `-- name: Dreadnought :one
SELECT hp, updated_at FROM dreadnought WHERE id = 1
`

type DreadnoughtRow struct {
	Hp        int64
	UpdatedAt int64
}

func (q *Queries) Dreadnought(ctx context.Context) (DreadnoughtRow, error) {
	row := q.db.QueryRowContext(ctx, dreadnought)
	var i DreadnoughtRow
	err := row.Scan(&i.Hp, &i.UpdatedAt)
	return i, err
}

const saveDreadnought = `-- name: SaveDreadnought :exec
INSERT INTO dreadnought (id, hp, updated_at) VALUES (1, ?, ?)
ON CONFLICT (id) DO UPDATE SET hp = excluded.hp, updated_at = excluded.updated_at
`

type SaveDreadnoughtParams struct {
	Hp        int64
	UpdatedAt int64
}

func (q *Queries) SaveDreadnought(ctx context.Context, arg SaveDreadnoughtParams) error {
	_, err := q.db.ExecContext(ctx, saveDreadnought, arg.Hp, arg.UpdatedAt)
	return err
}
