// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: frontier.sql

package db

import (
	"context"
)

const openRings = `-- name: OpenRings :one
SELECT open_rings FROM frontier WHERE id = 1
`

func (q *Queries) OpenRings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, openRings)
	var open_rings int64
	err := row.Scan(&open_rings)
	return open_rings, err
}

const saveOpenRings = `-- name: SaveOpenRings :exec
INSERT INTO frontier (id, open_rings) VALUES (1, ?)
ON CONFLICT (id) DO UPDATE SET open_rings = excluded.open_rings
`

func (q *Queries) SaveOpenRings(ctx context.Context, openRings int64) error {
	_, err := q.db.ExecContext(ctx, saveOpenRings, openRings)
	return err
}
