// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hangar.sql

package db

import (
	"context"
)

const hangar = `-- name: Hangar :one
SELECT ships FROM hangar WHERE id = 1
`

func (q *Queries) Hangar(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, hangar)
	var ships int64
	err := row.Scan(&ships)
	return ships, err
}

const saveHangar = `-- name: SaveHangar :exec
INSERT INTO hangar (id, ships) VALUES (1, ?)
ON CONFLICT (id) DO UPDATE SET ships = excluded.ships
`

func (q *Queries) SaveHangar(ctx context.Context, ships int64) error {
	_, err := q.db.ExecContext(ctx, saveHangar, ships)
	return err
}
