// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type ClearedSector struct {
	Name      string
	ClearedAt int64
}

type Frontier struct {
	ID        int64
	OpenRings int64
}

type Hangar struct {
	ID    int64
	Ships int64
}

type Player struct {
	ID         string
	Name       string
	TokenHash  string
	Weapon     string
	Engine     string
	Shield     string
	CreatedAt  int64
	LastSeenAt sql.NullInt64
}

type Unlock struct {
	PlayerID string
	Part     string
	Tier     int64
}
