// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type ClearedSector struct {
	Name      string
	ClearedAt int64
}

type Dreadnought struct {
	Faction   string
	Health    float64
	UpdatedAt int64
}

type Frontier struct {
	ID        int64
	OpenRings int64
}

type Hangar struct {
	ID    int64
	Ships int64
}

type Player struct {
	ID         string
	Name       string
	TokenHash  string
	Weapon     string
	Engine     string
	Shield     string
	CreatedAt  int64
	LastSeenAt sql.NullInt64
}

type Season struct {
	ID        int64
	StartedAt int64
	WonAt     sql.NullInt64
}

type SeasonStat struct {
	PlayerID       string
	Kills          int64
	CompanionKills int64
	Shots          int64
	Hits           int64
	Deaths         int64
	Rescues        int64
	Sectors        int64
}

type Unlock struct {
	PlayerID string
	Part     string
	Tier     int64
}
