// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: newseason.sql

package db

import (
	"context"
)

const forgetClearedSectors = `-- name: ForgetClearedSectors :exec
DELETE FROM cleared_sectors
`

func (q *Queries) ForgetClearedSectors(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, forgetClearedSectors)
	return err
}

const forgetDreadnoughts = `-- name: ForgetDreadnoughts :exec
DELETE FROM dreadnoughts
`

func (q *Queries) ForgetDreadnoughts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, forgetDreadnoughts)
	return err
}

const forgetFrontier = `-- name: ForgetFrontier :exec
DELETE FROM frontier
`

func (q *Queries) ForgetFrontier(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, forgetFrontier)
	return err
}

const forgetHangar = `-- name: ForgetHangar :exec
DELETE FROM hangar
`

func (q *Queries) ForgetHangar(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, forgetHangar)
	return err
}

const forgetLoadouts = `-- name: ForgetLoadouts :exec
UPDATE players SET weapon = '', engine = '', shield = ''
`

func (q *Queries) ForgetLoadouts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, forgetLoadouts)
	return err
}

const forgetStats = `-- name: ForgetStats :exec
DELETE FROM season_stats
`

func (q *Queries) ForgetStats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, forgetStats)
	return err
}

const forgetUnlocks = `-- name: ForgetUnlocks :exec
DELETE FROM unlocks
`

func (q *Queries) ForgetUnlocks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, forgetUnlocks)
	return err
}

const startSeason = `-- name: StartSeason :exec
UPDATE season SET started_at = ?, won_at = NULL WHERE id = 1
`

func (q *Queries) StartSeason(ctx context.Context, startedAt int64) error {
	_, err := q.db.ExecContext(ctx, startSeason, startedAt)
	return err
}
