// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"
	"database/sql"
)

const createPlayer = `-- name: CreatePlayer :exec
INSERT INTO players (id, name, token_hash, created_at) VALUES (?, ?, ?, ?)
`

type CreatePlayerParams struct {
	ID        string
	Name      string
	TokenHash string
	CreatedAt int64
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) error {
	_, err := q.db.ExecContext(ctx, createPlayer,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
	)
	return err
}

const deleteUnusedPlayers = `-- name: DeleteUnusedPlayers :execrows
DELETE FROM players WHERE last_seen_at IS NULL AND created_at <= ?
`

func (q *Queries) DeleteUnusedPlayers(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnusedPlayers, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const playerByTokenHash = `-- name: PlayerByTokenHash :one
SELECT id, name FROM players WHERE token_hash = ?
`

type PlayerByTokenHashRow struct {
	ID   string
	Name string
}

func (q *Queries) PlayerByTokenHash(ctx context.Context, tokenHash string) (PlayerByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, playerByTokenHash, tokenHash)
	var i PlayerByTokenHashRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const touchPlayer = `-- name: TouchPlayer :exec
UPDATE players SET last_seen_at = ? WHERE id = ?
`

type TouchPlayerParams struct {
	LastSeenAt sql.NullInt64
	ID         string
}

func (q *Queries) TouchPlayer(ctx context.Context, arg TouchPlayerParams) error {
	_, err := q.db.ExecContext(ctx, touchPlayer, arg.LastSeenAt, arg.ID)
	return err
}
