// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: season.sql

package db

import (
	"context"
	"database/sql"
)

const saveSeasonWon = `-- name: SaveSeasonWon :exec
UPDATE season SET won_at = ? WHERE id = 1 AND won_at IS NULL
`

func (q *Queries) SaveSeasonWon(ctx context.Context, wonAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, saveSeasonWon, wonAt)
	return err
}

const season = `-- name: Season :one
SELECT started_at, won_at FROM season WHERE id = 1
`

type SeasonRow struct {
	StartedAt int64
	WonAt     sql.NullInt64
}

func (q *Queries) Season(ctx context.Context) (SeasonRow, error) {
	row := q.db.QueryRowContext(ctx, season)
	var i SeasonRow
	err := row.Scan(&i.StartedAt, &i.WonAt)
	return i, err
}
