// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sectors.sql

package db

import (
	"context"
)

const clearSector = `-- name: ClearSector :exec
INSERT INTO cleared_sectors (name, cleared_at) VALUES (?, ?)
ON CONFLICT (name) DO NOTHING
`

type ClearSectorParams struct {
	Name      string
	ClearedAt int64
}

func (q *Queries) ClearSector(ctx context.Context, arg ClearSectorParams) error {
	_, err := q.db.ExecContext(ctx, clearSector, arg.Name, arg.ClearedAt)
	return err
}

const clearedSectors = `-- name: ClearedSectors :many
SELECT name FROM cleared_sectors ORDER BY name
`

func (q *Queries) ClearedSectors(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, clearedSectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
