// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
)

const saveStats = `-- name: SaveStats :exec
INSERT INTO season_stats (
    player_id, kills, companion_kills, shots, hits, deaths, rescues, sectors
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (player_id) DO UPDATE SET
    kills = excluded.kills,
    companion_kills = excluded.companion_kills,
    shots = excluded.shots,
    hits = excluded.hits,
    deaths = excluded.deaths,
    rescues = excluded.rescues,
    sectors = excluded.sectors
`

type SaveStatsParams struct {
	PlayerID       string
	Kills          int64
	CompanionKills int64
	Shots          int64
	Hits           int64
	Deaths         int64
	Rescues        int64
	Sectors        int64
}

func (q *Queries) SaveStats(ctx context.Context, arg SaveStatsParams) error {
	_, err := q.db.ExecContext(ctx, saveStats,
		arg.PlayerID,
		arg.Kills,
		arg.CompanionKills,
		arg.Shots,
		arg.Hits,
		arg.Deaths,
		arg.Rescues,
		arg.Sectors,
	)
	return err
}

const statsOf = `-- name: StatsOf :one
SELECT kills, companion_kills, shots, hits, deaths, rescues, sectors
FROM season_stats WHERE player_id = ?
`

type StatsOfRow struct {
	Kills          int64
	CompanionKills int64
	Shots          int64
	Hits           int64
	Deaths         int64
	Rescues        int64
	Sectors        int64
}

func (q *Queries) StatsOf(ctx context.Context, playerID string) (StatsOfRow, error) {
	row := q.db.QueryRowContext(ctx, statsOf, playerID)
	var i StatsOfRow
	err := row.Scan(
		&i.Kills,
		&i.CompanionKills,
		&i.Shots,
		&i.Hits,
		&i.Deaths,
		&i.Rescues,
		&i.Sectors,
	)
	return i, err
}
