// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
)

const allStats = `-- name: AllStats :many
SELECT p.id, p.name, s.kills, s.companion_kills, s.shots, s.hits, s.deaths, s.rescues, s.sectors
FROM season_stats s JOIN players p ON p.id = s.player_id
ORDER BY p.id
`

type AllStatsRow struct {
	ID             string
	Name           string
	Kills          int64
	CompanionKills int64
	Shots          int64
	Hits           int64
	Deaths         int64
	Rescues        int64
	Sectors        int64
}

func (q *Queries) AllStats(ctx context.Context) ([]AllStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, allStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllStatsRow
	for rows.Next() {
		var i AllStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kills,
			&i.CompanionKills,
			&i.Shots,
			&i.Hits,
			&i.Deaths,
			&i.Rescues,
			&i.Sectors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveStats = `-- name: SaveStats :exec
INSERT INTO season_stats (
    player_id, kills, companion_kills, shots, hits, deaths, rescues, sectors
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (player_id) DO UPDATE SET
    kills = excluded.kills,
    companion_kills = excluded.companion_kills,
    shots = excluded.shots,
    hits = excluded.hits,
    deaths = excluded.deaths,
    rescues = excluded.rescues,
    sectors = excluded.sectors
`

type SaveStatsParams struct {
	PlayerID       string
	Kills          int64
	CompanionKills int64
	Shots          int64
	Hits           int64
	Deaths         int64
	Rescues        int64
	Sectors        int64
}

func (q *Queries) SaveStats(ctx context.Context, arg SaveStatsParams) error {
	_, err := q.db.ExecContext(ctx, saveStats,
		arg.PlayerID,
		arg.Kills,
		arg.CompanionKills,
		arg.Shots,
		arg.Hits,
		arg.Deaths,
		arg.Rescues,
		arg.Sectors,
	)
	return err
}

const statsOf = `-- name: StatsOf :one
SELECT kills, companion_kills, shots, hits, deaths, rescues, sectors
FROM season_stats WHERE player_id = ?
`

type StatsOfRow struct {
	Kills          int64
	CompanionKills int64
	Shots          int64
	Hits           int64
	Deaths         int64
	Rescues        int64
	Sectors        int64
}

func (q *Queries) StatsOf(ctx context.Context, playerID string) (StatsOfRow, error) {
	row := q.db.QueryRowContext(ctx, statsOf, playerID)
	var i StatsOfRow
	err := row.Scan(
		&i.Kills,
		&i.CompanionKills,
		&i.Shots,
		&i.Hits,
		&i.Deaths,
		&i.Rescues,
		&i.Sectors,
	)
	return i, err
}
