// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: unlocks.sql

package db

import (
	"context"
)

const saveUnlock = `-- name: SaveUnlock :exec
INSERT INTO unlocks (player_id, part, tier) VALUES (?, ?, ?)
ON CONFLICT (player_id, part) DO UPDATE SET tier = excluded.tier
`

type SaveUnlockParams struct {
	PlayerID string
	Part     string
	Tier     int64
}

func (q *Queries) SaveUnlock(ctx context.Context, arg SaveUnlockParams) error {
	_, err := q.db.ExecContext(ctx, saveUnlock, arg.PlayerID, arg.Part, arg.Tier)
	return err
}

const unlocksOf = `-- name: UnlocksOf :many
SELECT part, tier FROM unlocks WHERE player_id = ?
`

type UnlocksOfRow struct {
	Part string
	Tier int64
}

func (q *Queries) UnlocksOf(ctx context.Context, playerID string) ([]UnlocksOfRow, error) {
	rows, err := q.db.QueryContext(ctx, unlocksOf, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnlocksOfRow
	for rows.Next() {
		var i UnlocksOfRow
		if err := rows.Scan(&i.Part, &i.Tier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
